version: '3.9'

services:
  app_1:
    build:
      context: ./products-app
    environment:
      - SPRING_PROFILES_ACTIVE=no_cache
    ports:
      - "8081:8080"
    networks:
      - app-network

  app_2:
    build:
      context: ./products-app
    environment:
      - SPRING_PROFILES_ACTIVE=map_cache
    ports:
      - "8082:8080"
    networks:
      - app-network

  app_3:
    build:
      context: ./products-app
    environment:
      - SPRING_PROFILES_ACTIVE=caffeine_cache
    ports:
      - "8083:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app_1
      - app_2
      - app_3
    networks:
      - app-network

networks:
  app-network: