version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    command:
      - '--config.file=/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    depends_on:
      - spring-boot-app
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring_net
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      
networks:
  monitoring_net:
    driver: bridge
volumes:
  grafana_data: