version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-4
    build:
      context: .
      dockerfile: jenkins/Dockerfile.jenkins
    ports:
      - "8085:8080"
      - "5665:5665"
      - "8081:8081"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: